// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_LaFnGFByIScaqZFCBgUeQ6f4PLgJrfA',
    appId: '1:511527805168:web:052fe29ee2e2ff0a51a235',
    messagingSenderId: '511527805168',
    projectId: 'bills-app-7e033',
    authDomain: 'bills-app-7e033.firebaseapp.com',
    storageBucket: 'bills-app-7e033.firebasestorage.app',
    measurementId: 'G-NFZFTGBT99',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkf5RH9LlrX0cZbiYdXOsN6j_tq46iFaE',
    appId: '1:511527805168:android:863e50c6da39bfae51a235',
    messagingSenderId: '511527805168',
    projectId: 'bills-app-7e033',
    storageBucket: 'bills-app-7e033.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJk-s3jxhom7ZmfOyvxR50MuZTUovbaqk',
    appId: '1:511527805168:ios:f18172449d5923ab51a235',
    messagingSenderId: '511527805168',
    projectId: 'bills-app-7e033',
    storageBucket: 'bills-app-7e033.firebasestorage.app',
    iosBundleId: 'com.example.bills',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJk-s3jxhom7ZmfOyvxR50MuZTUovbaqk',
    appId: '1:511527805168:ios:f18172449d5923ab51a235',
    messagingSenderId: '511527805168',
    projectId: 'bills-app-7e033',
    storageBucket: 'bills-app-7e033.firebasestorage.app',
    iosBundleId: 'com.example.bills',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_LaFnGFByIScaqZFCBgUeQ6f4PLgJrfA',
    appId: '1:511527805168:web:745a8641d009773c51a235',
    messagingSenderId: '511527805168',
    projectId: 'bills-app-7e033',
    authDomain: 'bills-app-7e033.firebaseapp.com',
    storageBucket: 'bills-app-7e033.firebasestorage.app',
    measurementId: 'G-5Q8ZKP8WF1',
  );
}
