// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiGpSWIznhjuH2aJ7f90lrGbtCojveNKA',
    appId: '1:315528552147:web:341cba3c00888ae7b0be26',
    messagingSenderId: '315528552147',
    projectId: 'bills-app-2a7e8',
    authDomain: 'bills-app-2a7e8.firebaseapp.com',
    storageBucket: 'bills-app-2a7e8.firebasestorage.app',
    measurementId: 'G-3BQESYYFKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACb-QotV3nay_EtVbmxWRtktyBs5vjwOM',
    appId: '1:315528552147:android:2104e2671508534bb0be26',
    messagingSenderId: '315528552147',
    projectId: 'bills-app-2a7e8',
    storageBucket: 'bills-app-2a7e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAn0gpNIhD5uKmqydzRVEslMmSepH8voc',
    appId: '1:315528552147:ios:23bcc6cf999bdb48b0be26',
    messagingSenderId: '315528552147',
    projectId: 'bills-app-2a7e8',
    storageBucket: 'bills-app-2a7e8.firebasestorage.app',
    iosBundleId: 'com.example.bills',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAn0gpNIhD5uKmqydzRVEslMmSepH8voc',
    appId: '1:315528552147:ios:23bcc6cf999bdb48b0be26',
    messagingSenderId: '315528552147',
    projectId: 'bills-app-2a7e8',
    storageBucket: 'bills-app-2a7e8.firebasestorage.app',
    iosBundleId: 'com.example.bills',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiGpSWIznhjuH2aJ7f90lrGbtCojveNKA',
    appId: '1:315528552147:web:97fd0cf73f8c9486b0be26',
    messagingSenderId: '315528552147',
    projectId: 'bills-app-2a7e8',
    authDomain: 'bills-app-2a7e8.firebaseapp.com',
    storageBucket: 'bills-app-2a7e8.firebasestorage.app',
    measurementId: 'G-67963QR827',
  );

}